### PR TITLE
Use CSS clamp for fluid font sizes

### LINKED ISSUE #17: Make style responsive
Change hard-coded widths depend on size of screen.

### PR DESCRIPTION
**Pull request by eflisback**
Fixes #17 

This update enables text in buttons, `pre` elements, paragraphs (`p`), and inputs to scale responsively with screen width, while capping sizes between 1 and 2 REM. By avoiding pure viewport width (`vw`) units, it preserves users' ability to zoom without issues.

I've done some testing myself using the built in Firefox **Responsive Device Mode**, but would appreciate if someone else also could take an extra look.

### CODE REVIEW

**Comment by eflisback** [comment]
I've also noticed that we're using media queries for `h1` elements. This could also be replaced with a clamp, but with some adjusted values. In my opinion that would be more consistent with these changes and also reduce the amount of code in `styles.css`.

**Comment by bjornregnell** [comment]
would you like to test this @trilleplay @JohanbcEkberg

**Comment by bjornregnell** [comment]
@eflisback Thanks!  I haven't seen clamp before and I'm obviously no css guru :) but I wonder if this is compatible also with old versions of browsers out there?

**Comment by eflisback** [comment]
That's a good question. Based on some blogs it's pretty standard to use, and according to [caniuse.com](https://caniuse.com/?search=clamp()) (which is an awesome site that provides browser compatibility info), it seems good! All major browsers support it, but if you have a version that's several years old it may not work.

**Comment by bjornregnell** [comment]
Thanks for the investigation! Yes a fallback would be good to have.

**Comment by eflisback** [comment]
Got it! And regarding the h1 media query I mentioned in the first comment?

**Comment by bjornregnell** [comment]
I don't even know what a media query is (I probably just copy-pasted it from somewhere). Can you explain why clamp is better? Anyway if the change is local to the css and it still Just Works (TM) then I'm fine with whatever :)

**Comment by eflisback** [comment]
Ah, yes. Sorry. Media queries can be used for a lot of things, but in this case we're using it to set a font size based on a number of different screen widths. Think of it as a match/case statement. 

- Case "screen width lower than a pixels": font size set to x pixels
- Case "screen width between a pixels and b pixels": font size set to y pixels 

And so on. 

I think the main perk with using a clamp instead is that it makes the font size scaling a lot "smoother". We don't need to define one specific case for each font size variation we want. And the more obvious perk is that it requires a lot less code :)

[This guy](https://dev.to/ericus123/why-you-should-use-clamp-over-media-queries-8og) dives into it a little deeper if you're interested 😄

**Comment by bjornregnell** [comment]
Many thanks for the pointers - I learned something new today!

Yes, please add a commit with clamp instead of media query and I'll merg it so we can test it all live with the many devices that students will use. Let's be [plucky](https://www.omgubuntu.co.uk/2024/10/ubuntu-25-04-codename-revealed) :)

**Comment by eflisback** [comment]
I've made the changes with two things to mention:

1. There's already a default fallback font-size for the elements. If there's a very old browser using this website, the clamp usage just simply won't affect the styling, but instead the browser will keep the default font-size for the element. Therefore I decided not to specify a fallback value before each clamp. 

2. I noticed that you're using some `h2` and `h3` elements as well in the "All questions" section. For consistency, I also gave them clamps so that they now also are responsive :)

Let me know what you think.

**Comment by bjornregnell** [comment]
Many thanks for your contribution to muntabot! @eflisback

**Pull request merged**
