### PR TITLE
Scala theme CSS modifications

### PR DESCRIPTION
**Pull request by eflisback**
Modified CSS to align its appearance more closely with the Scala language aesthetic. Buttons and anchor tags have been styled accordingly, and slight adjustments to 'pre' element. Also added sweet hover effect to the anchor tags using :hover::after selector.

**Before**
image

**After**
image

### CODE REVIEW

**Comment by bjornregnell** [comment]
Looks cool! I might let students vote on tomorrows lecture on which style they prefer :)
I'm a bit worried how color-blind might experience a potentially low contrast with red on pink but maybe that's not an issue. Perhaps the red could be a bit darker to increase contrast?

**Comment by bjornregnell** [comment]
@eflisback How come you closed it?

**Comment by eflisback** [comment]
Hey, yes. I was looking back at a few things which I regret regarding how I made the suggested styling changes. I will come back with a new pull request soon!

**Comment by bjornregnell** [comment]
OK good. No hurries.

**Pull request closed without merging**
